<ul id="menu">
<li> <a href="test3.php">Home</a> </li>
<li> <a href="test3.php?page=about">About Us</a> </li>
<li> <a href="test3.php?page=contact">Contact Us</a> </li>
</ul>
<?php
/*
* Very basic security measure to ensure that
* the page variable has been passed, enabling you to
* ward off very basic mischief using htmlentities()
*/
if(isset($_GET['page'])) {
$page = htmlentities($_GET['page']);
} else {
$page = NULL;
}
switch($page) {
case 'about':
echo "
<h1> About Us </h1>
<p> We are rockin' web developers! </p>";
break;
case 'contact':
echo "
<h1> Contact Us </h1>
<p> Email us at
<a href=\"mailto:info@example.com\">
info@example.com
</a>
</p>";
break;
/*
* Create a default page in case no variable is passed
*/
default:
echo "
<h1> Select a Page! </h1>
<p>
Choose a page from above
to learn more about us!
</p>";
break;
}
?>
<br><br><br>



<?php
/*
* Checks if the form was submitted
*/
if($_SERVER['REQUEST_METHOD'] == 'POST' AND htmlentities($_POST['username'])!="" AND htmlentities($_POST['email'])!="") {

	// Displays the submitted information
	echo "Thanks for registering! <br />",
	"Username: ", htmlentities($_POST['username']), "<br />",
	"Email: ", htmlentities($_POST['email']), "<br />";
} else {
	// If the form was not submitted, displays the form
?>

<form action="test3.php" method="post">
<p>Nu ati completat inca</p>
<label for="usern">Username:</label>
<input type="text" name="username" />
<label for="email">Email:</label>
<input type="text" name="email" />
<input type="submit" value="Register!" />
</form>

<?php } // End else statement ?>

<?php echo '<p><b>'; ?>
This text is enclosed in paragraph tags that were generated by PHP.
<?php echo '</b></p>'; ?>